
short-description: A basic hello-world instance-setup that shows how to run a cloud-config script.

cloud-init-user-data: |
  #cloud-config

  packages:
    - cowsay

  runcmd:
    - |
      cowsay "hello world from Cloudy!" > /tmp/hello-from-cloudy
