
short-description: A basic hello-world instance-setup that shows how to run a cloud-config script.

cloud-init-user-data: |
  #cloud-config

  packages:
    - cowsay

  runcmd:
    - |
      /usr/games/cowsay "hello world from Cloudy!" > /hello-from-cloudy
