name: cloudy build and test

on:
  pull_request:
  push:
    branches: [master]
    # tags: ['v*']  # Run on tag creation for new releases
  release:
    types: [ "published" ]

env:
  CI_RELEASE: "${{ github.event_name == 'release' }}"

# TODO: The cabal and stack actions currently don't cache built deps at all
# (even though the current code was working perfectly well in
# haskell/actions...)
#
# See the following for more info:
# - https://github.com/haskell-actions/setup#model-cabal-workflow-with-caching
# - https://github.com/haskell-actions/setup/issues/86

jobs:
  cabal:
    name: cabal / ghc-${{matrix.ghc}} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macOS-latest
        cabal: ["latest"]
        ghc:
          - "9.4.8"
          - "9.6.6"
          - "9.8.2"
          # - "9.10.1"

    steps:
    - uses: actions/checkout@v2
      #if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v3
      name: Cache cabal-store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: Build
      run: |
        cabal update
        cabal build --enable-tests --enable-benchmarks --write-ghc-environment-files=always

    - name: Test
      run: |
        cabal test --enable-tests

  stack:
    name: stack ${{ matrix.resolver }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["latest"]
        resolver:
          - "--stack-yaml ./stack-ghc-9.4.yaml"
          - "--stack-yaml ./stack.yaml" # GHC 9.6

    steps:
    - uses: actions/checkout@v2
      #if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: haskell-actions/setup@v2
      name: Setup Haskell Stack
      with:
        stack-version: ${{ matrix.stack }}
        enable-stack: true

    - uses: actions/cache@v3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.resolver }}-stack

    - name: Build
      run: |
        stack build ${{ matrix.resolver }} --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test ${{ matrix.resolver }}

  nix:
    name: nix / ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: nix-build

      - run: nix-build shell.nix

  nix-static:
    name: nix static / ubuntu-latest

    permissions:
      # This is required for this job to be able to upload release assets.
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - run: nix-build ./nix -A cloudy-static-just-exe

      - name: "(Release only) Publish statically-linked Linux x86_64 binary"
        if: "${{ env.CI_RELEASE == 'true' }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          static_bin="cloudy-static-linux-x86_64"
          cp ./result/bin/cloudy "${static_bin}"
          gh release upload --clobber "${{ github.ref_name }}" "${static_bin}"
